sudo: false

language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"

install:
  - pip install pipenv
  - pipenv install

script:
  - py.test tests
  # runs coverage
  - coverage run --source pysnips -m py.test tests/
  # - coverage report
  - coverage xml -i
  - coverage html -i
  - python-codacy-coverage -r coverage.xml
  - codecov

after_success:
  - bash <(curl -s https://codecov.io/bash)